[timer]
# Timer will stop and reset when you are idle for this amount of seconds.
idle_timeout = 240

# Get up, walk upstairs, look down street.
short_break_timeout = 900
short_break_duration = 120

# Get up, walk to river valley stairs, come back.
long_break_timeout = 3120
long_break_duration = 1020

[notification]
show_progress_bar = true
# Minimum delay of updating the progress bar (lower than 1s may return an error).
minimum_update_delay = 1
