bar:
  height: 30
  location: top
  background: 000000ff
  center:
    - clock:
        font: "Dina:pixelsize=14"
        date-format: "%d/%m/%Y"
        content:
          - string: {text: "{time} {date}"}
